menu:
  - name: Home
    url: /
  - name: 分类
    url: /categories/
  - name: 标签
    url: /tags/
  - name: 归档
    url: /archives/
  - name: Friends
    url: /friends/

socialLink:
  - name: Github
    link: https://github.com/govipg/

friends:
  - name: 旧梦
    avatar: //imgs.izou.top/user/avatar.jpg
    link: //blog.izou.top
    desc: 冰冻三尺非一日之寒，滴水穿石非一日之功

footer:
  builtUpTime: 2024-05-28

comment:
  enable: true
  type: giscus

giscus:
  repo: govipg/blog
  repoid: R_kgDONKkZZg
  category: General
  categoryid: DIC_kwDONKkZZs4Cj_EQ
  mapping: pathname
  strict: "0"
  reactionsenabled: "1"
  emitmetadata: "0"
  inputposition: bottom
  loading: lazy